name: chainapp
description: "A new Flutter project."
# Bu satır, yanlışlıkla yayınlamayı engeller.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Birleştirilmiş Firebase ve diğer paketler
  firebase_core: ^2.15.1
  firebase_auth: ^4.5.1
  cloud_firestore: ^4.7.1
  firebase_messaging: ^14.7.10 
  google_sign_in: ^6.2.1 # Arkadaşınızdan gelen paket
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Arkadaşınızdan gelen assets tanımları
  assets:
    - assets/images/hsl.login/hsl.jpg
    - assets/images/panda/